---
apiVersion: v1
kind: Service
metadata:
  name: dice-auto
spec:
  selector:
    app: dice-auto
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dice-auto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dice-auto
  template:
    metadata:
      labels:
        app: dice-auto
      annotations:
        instrumentation.opentelemetry.io/inject-java: "true"        
    spec:
      containers:
        - name: dice-auto
          image: dice:auto
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
