{{- $values := (mustMergeOverwrite .Values.service (or .Values.agent dict)) -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lgtm.fullname" . }}
  labels:
    {{- include "lgtm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.name }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
{{- range $portMap := $values.extraPorts }}
    - name: {{ $portMap.name }}
      port: {{ $portMap.port }}
      targetPort: {{ $portMap.targetPort }}
      protocol: {{ coalesce $portMap.protocol "TCP" }}
      {{- if not (empty $portMap.appProtocol) }}
      # Useful for OpenShift clusters that want to expose Alloy ports externally
      appProtocol: {{ $portMap.appProtocol }}
      {{- end }}
{{- end }}
  selector:
    {{- include "lgtm.selectorLabels" . | nindent 4 }}
