apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prom
  namespace: lgtm
spec:
  ingressClassName: traefik
  rules:
  - host: prometheus.local
    http:
      paths:
      - backend:
          service:
            name: lgtm-single
            port:
              number: 9090
        path: /
        pathType: ImplementationSpecific
